# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07747b1cf5ca9fc024402dd9faf66340ebb9de4fdf79281c55b81fb92758f87444f90c7e553f1ee68d1caa75dc4ecff5fac0ae49604a042ec544ce441ccb9cb6

test:
  secret_key_base: f23210b694795e696683a7ad34ac54f0621a051c747249055cb2267925dfad8b3bbfe094e8dc39906c40c56e7c9da1f1ef69217ece68a50c1d328e3128951a98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
